### ISSUE TITLE
error when generating markdown from tests/openapi3/api-with-examples.yaml

### ISSUE THREAD

**Issue by pitpit** [fmvilas/openapi3-generator#23]
Command:
```
node cli.js tests/openapi3/api-with-examples.yaml markdown
```

results in:
```
TypeError: Cannot read property 'allOf' of undefined
    at resolveAllOf (/Users/d.pitard/workspace/openapi3-generator/lib/beautifier.js:17:14)
    at beautifySchema (/Users/d.pitard/workspace/openapi3-generator/lib/beautifier.js:54:3)
    at _.each (/Users/d.pitard/workspace/openapi3-generator/lib/beautifier.js:104:11)
    at /Users/d.pitard/workspace/openapi3-generator/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/Users/d.pitard/workspace/openapi3-generator/node_modules/lodash/lodash.js:2996:24)
    at /Users/d.pitard/workspace/openapi3-generator/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/Users/d.pitard/workspace/openapi3-generator/node_modules/lodash/lodash.js:9344:14)
    at _.each (/Users/d.pitard/workspace/openapi3-generator/lib/beautifier.js:103:11)
    at /Users/d.pitard/workspace/openapi3-generator/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/Users/d.pitard/workspace/openapi3-generator/node_modules/lodash/lodash.js:2996:24)
```

with:

![image](https://user-images.githubusercontent.com/283481/59755409-24ac7400-9288-11e9-880c-2d60e4a88078.png)

**Comment by pitpit** [comment]
fixed here #24
