### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by tobiasstraub** [fmvilas/openapi3-generator#4]
After installing the generator and try the example commands to start the generator, I get the following error:
TypeError: Cannot read property 'length' of undefined
    at sharedStart (/usr/local/lib/node_modules/openapi3-generator/lib/beautifier.js:8:45)
    at module.exports (/usr/local/lib/node_modules/openapi3-generator/lib/beautifier.js:177:24)
    at bundle.catch.then (/usr/local/lib/node_modules/openapi3-generator/lib/generator.js:284:17)
    at <anonymous>

**Comment by fmvilas** [comment]
Hey @tobiasstraub!

Could you please provide an example of an AsyncAPI document to reproduce the error?
